import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import { Providers } from "./providers";

import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const josfin = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HireLoop | Job Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body data-theme="dark" className="dark bg-background text-foreground">
        <Providers>
          <Navbar/>
          {children}</Providers>
      </body>
    </html>
  );
}
