import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HireLoop | Job Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body data-theme="dark" className={` ${inter.className} dark bg-background text-foreground`}>
        <Providers>
          <Navbar/>
          {children}
          <Footer/>
          </Providers>
      </body>
    </html>
  );
}
